name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven

      - name: Build with Maven
        run: mvn clean install

      - name: Run tests with Maven
        run: mvn test

      - name: Parse test results
        run: |
          PASSED=$(grep -oP '(?<=<testsuite name=").*? tests="\K\d+(?=" skipped="0" failures="0" errors="0")' target/surefire-reports/*.xml | paste -sd+ | bc)
          echo "PASSED=$PASSED" >> $GITHUB_ENV

      - name: Create test badge
        run: |
          curl -s "https://img.shields.io/badge/tests_passed-${PASSED}-brightgreen" -o badge.svg
          chmod 777 badge.svg

      - name: List directory contents
        run: ls -la

      - name: Print badge.svg content
        run: cat badge.svg

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Update README
        run: |
          # Ensure badge.svg exists (optional)
          if [ ! -f "badge.svg" ]; then
            echo "Error: badge.svg not found. Skipping update."
            exit 0
          fi

          sed -i "s|tests_passed-[0-9]*-brightgreen|![test results](badge.svg)|" README.md
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md badge.svg
          git commit -m "Update test results badge"
          git push
        env:
          GIT_AUTHOR_NAME: github-actions[bot]
          GIT_AUTHOR_EMAIL: github-actions[bot]@users.noreply.github.com
          GIT_COMMITTER_NAME: github-actions[bot]
          GIT_COMMITTER_EMAIL: github-actions[bot]@users.noreply.github.com
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}

